# Use the official Python 3.11 image as the base image
FROM python:3.11 AS base

RUN apt-get update

# Install Node.js version 22
RUN apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

# Install the required system packages
RUN apt-get install -y ffmpeg git cmake gfortran libopenblas-dev

RUN apt-get clean

# Install pip dependencies
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --upgrade cython Cython
RUN pip install --no-cache-dir git+https://github.com/CPJKU/madmom

# Set the working directory for the backend
WORKDIR /app/backend

# Copy backend requirements and install dependencies
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code
COPY backend/ .

# Frontend build stage
FROM node:22 AS frontend-build

# Set the working directory for the frontend
WORKDIR /app/frontend

# Copy frontend package files and install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the rest of the frontend code
COPY frontend/ .

# Build the frontend application
RUN npm run build

# Final stage to combine both frontend and backend
FROM base

# Copy built frontend from the frontend-build stage
COPY --from=frontend-build /app/frontend /app/frontend

# Copy backend from the backend stage
COPY --from=base /app/backend /app/backend

# Set the working directory
WORKDIR /app

# Expose ports for frontend and backend
EXPOSE 3000 5001

# Start both frontend and backend
CMD ["sh", "-c", "cd /app/backend && python app.py & cd /app/frontend && npm run start"]