services:
  backend:
    image: public.ecr.aws/u4p9h6o7/mhuang74/infinite-worship:infinite-worship-backend-arm64-latest
    ports:
      - "5001:5001"
    volumes:
      - ./backend/uploads:/app/backend/uploads # Persist uploads
    environment:
      - PYTHONUNBUFFERED=1 # Ensure Python output is unbuffered
  frontend:
    image: public.ecr.aws/u4p9h6o7/mhuang74/infinite-worship:infinite-worship-frontend-arm64-latest
    ports:
      - "80:3000" # Map host port 80 to Nginx container port 3000
    depends_on:
      - backend # Frontend depends on backend for API calls
