# Use the official Python 3.11 image as the base image
FROM python:3.11 AS base

RUN apt-get update

# Install Node.js version 22
RUN apt-get install -y curl xz-utils && \
    curl -fsSL https://nodejs.org/dist/v22.12.0/node-v22.12.0-linux-arm64.tar.xz | tar -xJ -C /usr/local --strip-components=1



# Install the required system packages
RUN apt-get install -y ffmpeg git cmake gfortran libopenblas-dev

RUN apt-get clean

# Install pip dependencies
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --upgrade cython Cython
RUN pip install --no-cache-dir git+https://github.com/CPJKU/madmom

# Set the working directory for the backend
WORKDIR /app/backend

# Copy backend requirements and install dependencies
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Set the working directory
WORKDIR /app

# Expose ports for frontend and backend
EXPOSE 3000 5001

# Sleep on startup
CMD ["sh", "-c", "sleep infinity"]
